### ISSUE TITLE
build error. Getting  error: unknown file type '.pyx' (from 'midi.pyx')

### ISSUE THREAD

**Issue by guysoft** [b3b/midistream#1]
Full output:
```
Building wheels for collected packages: midistream
  Running command Building wheel for midistream (pyproject.toml)
  Ignoring "sys._home = value" override
  error: unknown file type '.pyx' (from 'midi.pyx')
  error: subprocess-exited-with-error
  
  × Building wheel for midistream (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/venv/bin/python /buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmporhbsnac
  cwd: /tmp/pip-req-build-rp2j23sf
  Building wheel for midistream (pyproject.toml) ... error
  ERROR: Failed building wheel for midistream
Failed to build midistream
ERROR: Could not build wheels for midistream, which is required to install pyproject.toml-based projects


  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/p4a/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/p4a/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/p4a/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/p4a/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/p4a/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/p4a/pythonforandroid/build.py", line 528, in build_recipes
    run_pymodules_install(
  File "/p4a/pythonforandroid/build.py", line 757, in run_pymodules_install
    shprint(sh.bash, '-c', (
  File "/p4a/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 915, in next
    self.wait()
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bash -c 'venv/bin/pip install -v --target '"'"'/buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/easinstrument/armeabi-v7a'"'"' --no-deps -r requirements.txt'

  STDOUT:
Ignoring "sys._home = value" override
Using pip 23.2.1 from /buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/venv/lib/python3.10/site-packages/pip (python 3.10)
Collecting https://github.com/b3b/midistream/archive/master.zip (from -r requirements.txt (line 3))
  Downloading https://github.com/b3b/midistream/archive/master.zip
     \ 30.8 kB 328.2 kB/s 0:00:00
  Running command pip subprocess to install build dependencies
  Ignoring "sys._home = value" override
  Collecting setuptools>=40.8.0
    Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl.metadata
    Using cached setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/17/11/f139e25018ea2218aeedbedcf85cd0dd8abeed29a38ac1fda7f5a8889382/wheel-0.41.0-py3-none-any.whl.metadata
    Using cached wheel-0.41.0-py3-none-any.whl.metadata (2.2 kB)
  Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Using cached wheel-0.41.0-py3-none-any.whl (64 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-68.0.0 wheel-0.41.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Ignoring "sys._home = value" override
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Ignoring "sys._home = value" override
  Preparing metadata (pyproject.toml) ... done
Collecting certifi (from -r requirements.txt (line 1))
  Obtaining dependency information for certifi from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting chardet (from -r requirements.txt (line 2))
  Downloading chardet-5.1.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 1.1 MB/s eta 0:00:00
Collecting idna (from -r requirements.txt (line 4))
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.2 MB/s eta 0:00:00
Collecting requests (from -r requirements.txt (line 5))
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting urllib3 (from -r requirements.txt (line 6))
  Obtaining dependency information for urllib3 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Downloading urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 5.8 MB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 13.8 MB/s eta 0:00:00
Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 10.1 MB/s eta 0:00:00
Building wheels for collected packages: midistream
  Running command Building wheel for midistream (pyproject.toml)
  Ignoring "sys._home = value" override
  error: unknown file type '.pyx' (from 'midi.pyx')
  error: subprocess-exited-with-error
  
  × Building wheel for midistream (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/venv/bin/python /buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmporhbsnac
  cwd: /tmp/pip-req-build-rp2j23sf
  Building wheel for midistream (pyproject.toml) ... error
  ERROR: Failed building wheel for midistream
Failed to build midistream
ERROR: Could not build wheels for midistream, which is required to install pyproject.toml-based projects


  STDERR:
```

**Comment by guysoft** [comment]
Fix in #3

**Comment by b3b** [comment]
#3 is merged. Thanks for the fix, @guysoft .

**Comment by guysoft** [comment]
Your welcome, better later then never :)
