### ISSUE TITLE
NameError: name 'mididriver' is not defined on app

### ISSUE THREAD

**Issue by guysoft** [b3b/midistream#2]
Hey,
Managed to compile and run on an androd device, but I get a dialog that reads:
```pythion
Error: <class 'NameError'>("name 'mididriver' is not defined",)
Traceback (most recent call last):
  File "/buildozer/.buildozer/android/app/main.py", line 45, in run
  File "/buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/easinstrument/arm64-v8a/kivy/app.py", line 955, in run
  File "/buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/easinstrument/arm64-v8a/kivy/app.py", line 950, in _run_prepare
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "/buildozer/.buildozer/android/app/main.py", line 36, in on_start
  File "/buildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/easinstrument/arm64-v8a/midistream/facade.py", line 40, in __init__
NameError: name 'mididriver' is not defined
```

**Comment by b3b** [comment]
Hey Guy,

Thanks for reporting. I haven't rebuilt for quite a while.
I'll try to rebuild with your PR, and will try to reproduce the "NameError".
Appreciate your contribution!

**Comment by b3b** [comment]
Fixed by the new installation method from #5.

`mididriver` and `p4a.local_recipes` are no longer required.
